### ISSUE TITLE
Endless Sky: 0.10.2 stable update available

### ISSUE THREAD

**Issue by opusforlife2** [mikeee/ChocoPackages#102]
Hi. The package can now be updated from 0.10.0 to 0.10.2.

**Comment by mikeee** [comment]
Hi! 

The package is automatically maintained and in this instance was submitted to the chocolatey package repo on the 19th of June. Unfortunately beyond submission it's up to the moderation process as to when it is made available.

You can install it prior to the approval process by using the steps on the package page: https://community.chocolatey.org/packages/endless-sky/0.10.2

If the package is rejected for whatever reason please reopen the issue.

Cheers,
Mike
