### ISSUE TITLE
[REQUEST] AWS-CLI

### ISSUE THREAD

**Issue by danielkomaz** [mikeee/ChocoPackages#11]
**Software details**
Name: aws-cli
URL/Website:
   - https://github.com/aws/aws-cli/releases
Download Link: 
   - Latest: https://awscli.amazonaws.com/AWSCLIV2.msi
   - Specific version: https://github.com/aws/aws-cli/releases/tag/2.1.28
Licence (if known): Apache License, Version 2.0

**Chocolatey**
 - [x] This package is not on Chocolatey already (https://chocolatey.org/packages)

**Comment by mikeee** [comment]
https://chocolatey.org/packages/awscli

There is already a chocolatey package for the app requested.
