### ISSUE TITLE
[BUG] Incorrect checksum for Pidgin 2.14.3

### ISSUE THREAD

**Issue by williamjacksn** [mikeee/ChocoPackages#15]
**Describe the Issue**

The checksum for Pidgin 2.14.3 is incorrect.

**Additional context**

https://github.com/mikeee/ChocoPackages/blob/44f4823ed893ebe44cda91479dc07a130d8db25a/automatic/pidgin/tools/chocolateyInstall.ps1#L6

This checksum should be:

```bash
# sha256sum pidgin-2.14.3-offline.exe
e9cf873c7c0f772f682425a2f52e60d8a6d928ee06f770ad06905b3f2d736ffe  pidgin-2.14.3-offline.exe
```

This incorrect checksum is causing the most recent submission to fail:

https://gist.github.com/choco-bot/12225d8789ee35505c5b57a1b49f499f

**Comment by mikeee** [comment]
Not really sure what caused this, the script works fine on my personal machine so I can only assume it has something to do with the CI. I've manually updated the packages and will be monitoring the CI more closely.
