### ISSUE TITLE
Corsair iCUE package 

### ISSUE THREAD

**Issue by mikeee** [mikeee/ChocoPackages#16]
The [Corsair iCUE package](https://community.chocolatey.org/packages/icue) does not currently update correctly as the source where this script pulls the latest version (from the main icue page) is not updated regularly by Corsair.

Proposed check location: https://www.corsair.com/uk/en/downloads

**Comment by JasonChillblast** [comment]
I'd love to see this updated 😊

**Comment by JasonChillblast** [comment]
Thanks, appreciated :)
