### ISSUE TITLE
Make Crystaldiskmark internal

### ISSUE THREAD

**Issue by TheCakeIsNaOH** [mikeee/ChocoPackages#6]
It would be nice if the crystaldiskmark package included the installer instead of downloading it at runtime, i.e. making it internal.

The total package size would be well under the limit of 200mb, and the crystaldiskmark license (MIT) allows redistribution, so there would be no legal or technical problem with doing so as far as I can see.

**Comment by mikeee** [comment]
Can you double check the expected functionality please? When installing the package I'm seeing the installer function correctly...

```Downloading crystaldiskmark
  from 'https://osdn.net/frs/redir.php?m=dotsrc&f=crystaldiskmark/71859/CrystalDiskMark7_0_0h.exe'
Progress: 100% - Completed download of C:\Users\Mike\AppData\Local\Temp\chocolatey\crystaldiskmark\7.0.0.104\CrystalDiskMark7_0_0h.exe (5.84 MB).
Download of CrystalDiskMark7_0_0h.exe (5.84 MB) completed.
Hashes match.
Installing crystaldiskmark...
crystaldiskmark has been installed.
  crystaldiskmark can be automatically uninstalled.
 The install of crystaldiskmark was successful.
  Software installed to 'C:\Program Files\CrystalDiskMark7\'```

**Comment by mikeee** [comment]
Oh I see what you mean, I don't aim to include executables with the package itself unless absolutely necessary. Following the normal conventions of distribution from a trusted source such as the originators mirrors is best in my opinion.

Are there any particularly strong reasons to package the executables and redistribute them?

**Comment by TheCakeIsNaOH** [comment]
> the normal conventions of distribution from a trusted source such as the originators mirrors

What is your source for this? All of the offical Chocolatey docs that I have found are neutral or slightly positive toward including the executables inside the package, assuming that the licensing and size are not prohibitive.

> Are there any particularly strong reasons to package the executables and redistribute them?

It makes the package more reliable and long-lasting. It also allows installation of the package on an offline machine, or one with filtered internet. 

The core team repository has a better write up.
https://github.com/chocolatey-community/chocolatey-coreteampackages/blob/master/CONTRIBUTING.md#114-embed-a-package-if-allowed

**Comment by mikeee** [comment]
Cheers for the references. I initially hadn't noticed that some of the packages in the core team's repository makes use of executables bundled in packages. Since the executables are small I'll get this package updated ready for the next release. I'll also push changes to any other of the packages managed by this repo that are suitable.

**Comment by TheCakeIsNaOH** [comment]
Awesome, thanks. Let me know if you need help or more resources/examples. 

Offhand, I took a peek at your other packages, and it looks like `golang`, `sqlite-studio`, `hcloud`, `pidgin`, `vultr-cli.portable` and `winmerge.portable` are all candidates for moving to internal, although some might be too large. 

If a package would be over 200mb with both 32 and 64 bit installers, but with just one would be under 200mb, it is permitted to only include one. Both calibre and krita packages are examples of this, as they include only the 64 bit installers, and have the 32 bit installer as a download. Also, they are both core team packages, so they are pretty much as officially sanctioned as packages get.  
https://chocolatey.org/packages/calibre#files
https://chocolatey.org/packages/krita#files
