### ISSUE TITLE
[BUG] WSL Manager not added to the start menu

### ISSUE THREAD

**Issue by silopolis** [mikeee/ChocoPackages#87]
First, big thanks for packaging softwares for Chocolatey, life behind Windows wouldn't be the same without your work and dedication 🙏 

**Describe the Issue**
After installing wsl2-distro-manager, no entry is added to the start menu, which, I believe, is an issue for a GUI app.
Also, but I'm uncertain if it belongs to here, the app icon is our beloved Tux instead of the app's logo.

**To Reproduce**
1. install software with `choco install wsl2-distro-manager`
2. Go to start menu
3; Feel the thrill of nothingness ;)

Cheers
J

**Comment by mikeee** [comment]
It'll be added as of 1.8.4 when it goes through the package review process.
