### ISSUE TITLE
[REQUEST] CrystalDiskMark (Portable)

### ISSUE THREAD

**Issue by Hlsgs** [mikeee/ChocoPackages#9]
Please make a portable version of CrystalDiskMark. Thank you!

**Comment by jpluimers** [comment]
@mikeee I can only provide a few tips, not a full script (see https://twitter.com/jpluimers and the pinned post there why).

Looking at https://github.com/mikeee/ChocoPackages/blob/master/automatic/crystaldiskmark/update.ps1 you already parse the `.zip` file to get the `.exe` file.

For the current version, that logic generates https://osdn.net/frs/redir.php?m=gigenet&f=crystaldiskmark/77936/CrystalDiskMark8_0_4c.exe

Using almost the same logic you get https://osdn.net/frs/redir.php?m=nchc&f=crystaldiskmark/77936/CrystalDiskMark8_0_4c.zip

After downloading, put it in the tools directory, then generate a shim for `DiskMark32.exe` and `DiskMark64.exe`.

There will probably be some logic required for uninstalling to ensure neither of these processes are active.

**Comment by mikeee** [comment]
> @mikeee I can only provide a few tips, not a full script (see https://twitter.com/jpluimers and the pinned post there why).
> 
> Looking at https://github.com/mikeee/ChocoPackages/blob/master/automatic/crystaldiskmark/update.ps1 you already parse the `.zip` file to get the `.exe` file.
> 
> For the current version, that logic generates https://osdn.net/frs/redir.php?m=gigenet&f=crystaldiskmark/77936/CrystalDiskMark8_0_4c.exe
> 
> Using almost the same logic you get https://osdn.net/frs/redir.php?m=nchc&f=crystaldiskmark/77936/CrystalDiskMark8_0_4c.zip
> 
> After downloading, put it in the tools directory, then generate a shim for `DiskMark32.exe` and `DiskMark64.exe`.
> 
> There will probably be some logic required for uninstalling to ensure neither of these processes are active.
> 
> 

Cheers! I'll be clearing most of the open issues soon, I've got a backlog of packages to update and maintain but will probably push this out around early Jan.

**Comment by jpluimers** [comment]
Hold this for a few weeks please. Lots of things going on in our lives right now.
